name: S3DF - Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
      - 'ondemand.sh'
      - 'Dockerfile.NERSC'
      - './NERSC_notebooks/**'
      - 'impact_bmad_NERSC.sh'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true 
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Fetch Git LFS files
        run: git lfs pull
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.s3df
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/facet2-bmad-pytao:latest
